### ISSUE TITLE
`abab` nolyfill causes a crash in `data-urls` package

### ISSUE THREAD

**Issue by wojtekmaj** [SukkaW/nolyfill#58] opened 2024-02-12 11:44 UTC
Using yarn-plugin-nolyfill@0.1.2, all tests were green.
Using yarn-plugin-nolyfill@0.1.3, I'm getting the following crash on my unit tests:

```
[react-pdf]: TypeError: Cannot destructure property 'atob' of 'require(...)' as it is undefined.
[react-pdf]:  ❯ Object.<anonymous> ../../node_modules/data-urls/lib/utils.js:2:9
[react-pdf]:  ❯ Module._compile node:internal/modules/cjs/loader:1241:14
[react-pdf]:  ❯ Object.Module._extensions..js node:internal/modules/cjs/loader:1295:10
[react-pdf]:  ❯ Module.load node:internal/modules/cjs/loader:1091:32
[react-pdf]:  ❯ Function.Module._load node:internal/modules/cjs/loader:938:12
[react-pdf]:  ❯ Module.require node:internal/modules/cjs/loader:1115:19
[react-pdf]:  ❯ require node:internal/modules/helpers:130:18
[react-pdf]:  ❯ Object.<anonymous> ../../node_modules/data-urls/lib/parser.js:4:93
[react-pdf]:  ❯ Module._compile node:internal/modules/cjs/loader:1241:14
[react-pdf]:  ❯ Object.Module._extensions..js node:internal/modules/cjs/loader:1295:10
```

Between these updates, 2 nolyfills were added:
* abab
* util.promisify

And out of these two, only `abab` was a candidate for replacement. This leads me to believe there's something wrong with `abab` nolyfill.

This issue may affect JSDOM and other projects. Dependency tree of mine:
```
└─ react-pdf@workspace:packages/react-pdf
   └─ jsdom@npm:21.1.1 [7b2c8] (via npm:^21.1.0 [7b2c8])
      ├─ abab@npm:2.0.6 (via npm:^2.0.6)
      └─ data-urls@npm:4.0.0 (via npm:^4.0.0)
         └─ abab@npm:2.0.6 (via npm:^2.0.6)
```

**Comment by SukkaW** [comment] 2024-02-12 12:34
The issue is caused by an implementation error of the export interop. It has been resolved by the commit https://github.com/SukkaW/nolyfill/commit/8580a1c4acacf46d9ed19f3ba9d0896e7241b120. Packages affected by this issue is being released with a new version `1.0.29`.

**Closed by SukkaW** 2024-02-12 12:34 UTC
